### ISSUE TITLE
Question: CORS issue

### ISSUE THREAD

**Issue by markjoeljimenez** [whatadewitt/fantasy-docs-next#7]
Hello!

Didn't want to create an issue in the [yahoo-fantasy-sports-api](https://github.com/whatadewitt/yahoo-fantasy-sports-api) repo as I'm not currently using it... but I was just wondering how you're getting around the CORS issue? I have a `nextjs` app with the `nextauth` package and have been able to successfully authenticate myself and store my access token. However, when I try to make calls to Yahoo's apis, I get a CORS error

```
Access to fetch at 'https://fantasysports.yahooapis.com/fantasy/v2/users;use_login=1/games?access_token=[ACCESS_TOKEN]' from origin 'https://auth-test.optidfs.com' 
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Are you using a proxy server?

**Comment by whatadewitt** [comment]
Sounds like you're trying to make a call from the browser? You need to make these calls from a Node backend. The security on the front end could be problematic.

**Comment by Wintersboy** [comment]
Regarding a previous issue I opened, I found the reason for the CORS error that I was facing. I don't know what your code looks like, but if you are calling the callback as an API call, it will throw a CORS error. Changing that call to an `href` worked for me. I think its because the callback returns a redirect, but I'm not positive of that reasoning. 

Let me know if this helps!

**Comment by whatadewitt** [comment]
Not sure I follow… do you have the code anywhere?

**Comment by Wintersboy** [comment]
Ahh sorry I deleted the comment as I realized it had nothing to do with this issue. But basically, the authentication callback throws a cors error when trying to `fetch` that API. Instead, an `href` worked.

**Comment by markjoeljimenez** [comment]
Yup, just had to make my API calls from my Node server. Thanks!

**Comment by whatadewitt** [comment]
@Wintersboy that's correct -- it's expected that you'd be redirected to kick off the oAuth flow

glad it's sorted :)
